### ISSUE TITLE
Further improvement

### ISSUE THREAD

**Issue by sebastian-code** [vitorfs/bootcamp#66]
Following the suggestions by @vitorfs and questions by @dwayne on #57 I wanted to set a list of potential improvements:

- [x] Migrate to Python 3.
- [x] Keep backwards compatibility with Python 2.
- [x] Add coverage (suggested on my most recent PR #65 as suggested in #48).
- [x] Add coveralls badge.
- [x] Add requirements monitoring (requires.io is the one I have in mind).
- [x] Add requires.io badge (that's because that's the service I know of)
- [x] Run isort on the project (well, this can be done by hand to, and I have cleaned a little bit already).
- [x] Run Flake8 on the project.
- [x] Polish the code structure applying a more 12-Factor style (as suggested in #55).
- [x] Add docker to the development flow (as suggested in #51).
- [x] Implement CBV (I actually have doubts about this one suggested in #50 but I guess than at least it should be discussed).
- [x] Implement better user management and it's workflow functionalities (password recovery, social networks integrations, account creation, login management, correct redirect) as suggested in #86, #53, #32, #28 and #2.
- [x] Add tests to the apps to validate functionality and that way incrementing test coverage, as suggested in #63 and complemented with the requirements from #48 and #65 which were already solved.
- [x] Add better tagging management. As suggested in #54, #73 and #74.
- [ ] Implement a nice release cycle on the project (I have to work on this because I'm not that really aware of how it works)
- [ ] Add Tox to the project.

On the next list I would define some additional requests, perhaps too old and somehow relegated to the _nice to have_ drawer:

- [x] Improve keyboard shortcut to submit comments, perhaps accepting _CMD + Enter_ on OS X, just like GitHub (As suggested in #29).
- [ ] Add User reputation system and its respective management process so it can be overrided (as defined on #19).
- [x] Implement better internationalization (a really wild idea, but who knows).
- [x] Display the list of users who liked a given feed, on hover (As requested on #21).
- [ ] Federate multiple instances of bootcamp (As suggested in #31).

Do you both have additional suggestions, requests or goals? As an example, badges are really nice, but there is no need to have all of them, do you have some ideas about which badges the project should have?

PD 4-12-16: Updating the list to include requirements monitoring and the proper badge.
PD 18-12-16: Updating the list to include the reputation system.
PD 13-05-17: Updating the list to include the requirement to add testing to apps.
PD 3-7-17: Updating the issue to add a list of _nice to have_ and forgotten requests.

**Comment by sebastian-code** [comment]
I'm honored @vitorfs for the invitation to collaborate.

**Comment by sebastian-code** [comment]
Hi @vitorfs I was trying to add requires.io to keep track of the requirements of the project. I'm not allowed to do it, but I would guess you can, so here is where we should think if that is a nice feature and useful somehow.

I would think than now I'm having a change of heart just because of frustration because I wasn't able to do it, but I would love to hear your opinion.

**Comment by vitorfs** [comment]
hey @sebastian-code! I really appreciate all the effort and your contributions to the project! :-)
I've added the requires.io badge in the README.md
We have some outdated requirements, but from what I've seen they are all easy to upgrate

**Comment by sebastian-code** [comment]
Hi @vitorfs and thanks for your compliments; it's my pleasure. I have been going around a little bit, but the requirements are already met, right now I finished implementing the Flake8 error report, is already in my development branch and I'm validating than everything works, which is how it looks as far as I can see.

**Comment by sebastian-code** [comment]
Updating after running Flake8 and applying the suggested changes. Do you mind to test it a little bit to see how it went?

**Comment by sebastian-code** [comment]
Ufff, docker implemented. I was believing it wasn't going to work. Silly me.

**Comment by chetanya-shrimali** [comment]
Hey, @sebastian-code is anyone still working on this " Display the list of users who liked a given feed, on hover (As requested on #21)". cuz I would like to send pr on this issue.

**Comment by sebastian-code** [comment]
Hi @chetanya-shrimali No than I'm aware of. I'll be delighted if you send one.

**Comment by norsec** [comment]
hi, i got a Social Auth System working with AllAuth Django, but was have to install the admin site to configure that. maybe we can include here?

**Comment by Allan-Nava** [comment]
I have included the admin panel with jet @norsec ! 
Badges are very interesting features!

**Comment by sebastian-code** [comment]
Milestone reached, closing this issue.
